<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <DefineConstants>FABLE_COMPILER;FABLE_COMPILER_JAVASCRIPT;FABLE_COMPILER_TYPESCRIPT</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DecodeMappingTest.fs" />
    <Compile Include="DecodeMappingSetTest.fs" />
    <Compile Include="EncodeMappingTest.fs" />
    <Compile Include="EncodeMappingSetTest.fs" />
    <Compile Include="EncodeSssomDocumentTest.fs" />
    <Compile Include="DecodeSssomDocumentTest.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.2.0" />
    <PackageReference Include="Fable.Python" Version="5.4.0" />
    <PackageReference Include="Fable.Pyxpecto" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SSSOM\SSSOM.JavaScript.fsproj" />
  </ItemGroup>

</Project>
