<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>PolyglotSSSOM.Python</AssemblyName>
    <RootNamespace>SSSOM</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <DefineConstants>FABLE_COMPILER;FABLE_COMPILER_PYTHON</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain\Enums.fs" />
    <Compile Include="Domain\LexicalValues.fs" />
    <Compile Include="Domain\Extensions.fs" />
    <Compile Include="Domain\CurieMap.fs" />
    <Compile Include="Domain\Descriptors.fs" />
    <Compile Include="Domain\Mapping.fs" />
    <Compile Include="Domain\MappingSet.fs" />
    <Compile Include="Domain\SssomDocument.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.2.0" />
    <PackageReference Include="Fable.Python" Version="5.4.0" />
    <PackageReference Include="YAMLicious" Version="1.0.0" />
  </ItemGroup>

</Project>
